# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
    - docker:dind
before_script:
    - echo "$GIT_REGISTRY_TOKEN" | docker login -u "$GIT_REGISTRY_USER" registry.gitlab.com --password-stdin
variables:
    VERSION: "0.0.24"
build-and-deploy:
    stage: build
    tags:
        - docker
    only:
        - tags
    script:
        - docker build --target amd64 -t registry.gitlab.com/iiis/backend/gateway:amd64-$VERSION .
        - docker push registry.gitlab.com/iiis/backend/gateway:amd64-$VERSION
        - docker build --target armv7 -t registry.gitlab.com/iiis/backend/gateway:armv7-$VERSION .
        - docker push registry.gitlab.com/iiis/backend/gateway:armv7-$VERSION
